# 

name: Psalm Security Scan

# Controls when the workflow will run

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Psalm for PHP
        uses: psalm/psalm-github-actions@2.3.0
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
         report_file: php
        
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v3
        with:
          name: psalm.sarif
          path: ${{runner.workspace}}/results/*.sarif
